export enum PackType {
  Classic = 'Classic',
  GoblinsVsGnomes = 'GoblinsVsGnomes',
  TheGrandTournament = 'TheGrandTournament',
  WhispersOfTheOldGods = 'WhispersOfTheOldGods',
  MeanStreetsOfGadgetzan = 'MeanStreetsOfGadgetzan',
  JourneyToUnGoro = 'JourneyToUnGoro',
  KnightsOfTheFrozenThrone = 'KnightsOfTheFrozenThrone',
  KoboldsAndCatacombs = 'KoboldsAndCatacombs',
  TheWitchwood = 'TheWitchwood',
  TheBoomsdayProject = 'TheBoomsdayProject',
  RastakhansRumble = 'RastakhansRumble',
  RiseOfShadows = 'RiseOfShadows',
  SaviorsOfUldum = 'SaviorsOfUldum',
  DescentOfDragons = 'DescentOfDragons',
  AshesOfOutland = 'AshesOfOutland',
  ScholomanceAcademy = 'ScholomanceAcademy',
  MadnessAtTheDarkmoonFaire = 'MadnessAtTheDarkmoonFaire',
  ForgedIntheBarrens = 'ForgedIntheBarrens',
  UnitedInStormwind = 'UnitedInStormwind',
  FracturedInAlteracValley = 'FracturedInAlteracValley',
  VoyageToTheSunkenCity = 'VoyageToTheSunkenCity',
  MurderAtCastleNathria = 'MurderAtCastleNathria',
  MarchOfTheLichKing = 'MarchOfTheLichKing',
  FestivalOfLegends = 'FestivalOfLegends',
  Titans = 'Titans',
  ShowdownInTheBadlands = 'ShowdownInTheBadlands'
}
